"""
train_physics_model.py

Trains the TrueTrack 1D-CNN on the 200 physics-grounded synthetic sessions
generated by physics_grounded_generator.py (176k timesteps, ~59 minutes of
two-wheeler driving data).
"""

import os
import glob
import json
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

class NeuralInertial1DCNN(nn.Module):
    def __init__(self):
        super(NeuralInertial1DCNN, self).__init__()
        # 6-Axis normalized IMU input: [Batch, 6, 50]
        self.feature_extractor = nn.Sequential(
            nn.Conv1d(in_channels=6, out_channels=32, kernel_size=5, padding=2),
            nn.BatchNorm1d(32),
            nn.LeakyReLU(0.1),
            nn.Conv1d(in_channels=32, out_channels=64, kernel_size=5, padding=2),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.1),
            nn.MaxPool1d(kernel_size=2),  # 50 -> 25
            nn.Conv1d(in_channels=64, out_channels=64, kernel_size=3, padding=1),
            nn.BatchNorm1d(64),
            nn.LeakyReLU(0.1),
            nn.AdaptiveAvgPool1d(1)       # 25 -> 1
        )
        self.regressor = nn.Sequential(
            nn.Linear(64, 32),
            nn.LeakyReLU(0.1),
            nn.Linear(32, 2)              # [forward_speed_m_s, yaw_rate_rad_s]
        )

    def forward(self, x):
        feat = self.feature_extractor(x)
        feat = feat.view(feat.size(0), -1)
        out = self.regressor(feat)
        return out

class PhysicsWindowDataset(Dataset):
    def __init__(self, sessions, means, stds, window_size=50, stride=3):
        self.X = []
        self.y = []
        
        for s in sessions:
            acc = s['accel'] # (N, 3): [ax, ay, az]
            gyro = s['gyro'] # (N, 3): [gx, gy, gz]
            raw = np.hstack([acc, gyro]) # (N, 6)
            
            # Normalize
            norm = (raw - means) / stds
            
            v = s['v_true']
            w = s['omega_true']
            targets = np.column_stack([v, w])
            
            N = len(norm)
            for i in range(0, N - window_size, stride):
                self.X.append(norm[i : i + window_size].T) # (6, 50)
                self.y.append(targets[i + window_size - 1])
                
        self.X = np.array(self.X, dtype=np.float32)
        self.y = np.array(self.y, dtype=np.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return torch.tensor(self.X[idx]), torch.tensor(self.y[idx])

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    batch_dir = os.path.join(base_dir, 'synthetic_batch')
    files = sorted(glob.glob(os.path.join(batch_dir, '*.npz')))
    
    if len(files) == 0:
        raise FileNotFoundError(f"No session files found in {batch_dir}")
        
    print(f"Loading {len(files)} physics-grounded sessions...")
    sessions = [np.load(f) for f in files]
    
    # 1. Compute global per-channel Z-score normalization statistics
    all_raw = np.vstack([np.hstack([s['accel'], s['gyro']]) for s in sessions])
    means = all_raw.mean(axis=0).astype(np.float32)
    stds = (all_raw.std(axis=0) + 1e-4).astype(np.float32)
    
    print("\nGlobal Normalization Statistics across 176k samples:")
    channel_names = ['ax', 'ay', 'az', 'gx', 'gy', 'gz']
    for name, m, s in zip(channel_names, means, stds):
        print(f"  {name:2s}: mean = {m:8.4f}, std = {s:8.4f}")
        
    stats_dict = {"means": means.tolist(), "stds": stds.tolist()}
    stats_path = os.path.join(base_dir, 'norm_stats.json')
    with open(stats_path, 'w') as f:
        json.dump(stats_dict, f, indent=2)
    print(f"Saved norm_stats.json to {stats_path}")
    
    # Also copy to Android assets
    android_assets_dir = os.path.join(os.path.dirname(base_dir), 'android_app', 'app', 'src', 'main', 'assets')
    if os.path.exists(android_assets_dir):
        with open(os.path.join(android_assets_dir, 'norm_stats.json'), 'w') as f:
            json.dump(stats_dict, f, indent=2)
        print("Updated android_app assets norm_stats.json")

    # 2. Build training dataset
    print("\nBuilding sliding window dataset (window=50, stride=3)...")
    dataset = PhysicsWindowDataset(sessions, means, stds, window_size=50, stride=3)
    print(f"Total window samples: {len(dataset):,}")
    
    train_size = int(0.85 * len(dataset))
    val_size = len(dataset) - train_size
    train_set, val_set = torch.utils.data.random_split(
        dataset, [train_size, val_size], generator=torch.Generator().manual_seed(42)
    )
    
    train_loader = DataLoader(train_set, batch_size=64, shuffle=True)
    val_loader = DataLoader(val_set, batch_size=64, shuffle=False)
    
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = NeuralInertial1DCNN().to(device)
    criterion = nn.MSELoss()
    optimizer = optim.AdamW(model.parameters(), lr=0.002, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=15)
    
    print(f"Training on {device} (15 epochs)...")
    best_val_loss = float('inf')
    best_weights_path = os.path.join(base_dir, 'truetrack_1dcnn.pth')
    
    for epoch in range(1, 16):
        model.train()
        train_loss = 0.0
        for X_b, y_b in train_loader:
            X_b, y_b = X_b.to(device), y_b.to(device)
            optimizer.zero_grad()
            pred = model(X_b)
            loss = criterion(pred, y_b)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * len(X_b)
        train_loss /= len(train_set)
        
        # Validation
        model.eval()
        val_loss = 0.0
        val_speed_err = 0.0
        with torch.no_grad():
            for X_b, y_b in val_loader:
                X_b, y_b = X_b.to(device), y_b.to(device)
                pred = model(X_b)
                loss = criterion(pred, y_b)
                val_loss += loss.item() * len(X_b)
                val_speed_err += torch.abs(pred[:, 0] - y_b[:, 0]).sum().item()
        val_loss /= len(val_set)
        val_mae = val_speed_err / len(val_set)
        scheduler.step()
        
        print(f"Epoch {epoch:2d}/15: Train Loss={train_loss:.4f}, Val Loss={val_loss:.4f}, Speed MAE={val_mae*3.6:.2f} km/h")
        
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), best_weights_path)
            
    print(f"\nBest Validation Loss: {best_val_loss:.4f}")
    
    # 3. Export to ONNX
    model.load_state_dict(torch.load(best_weights_path))
    model.eval()
    model.to('cpu')
    
    dummy_input = torch.randn(1, 6, 50, dtype=torch.float32)
    onnx_path = os.path.join(base_dir, 'truetrack_model.onnx')
    
    torch.onnx.export(
        model,
        dummy_input,
        onnx_path,
        export_params=True,
        opset_version=14,
        do_constant_folding=True,
        input_names=['imu_input'],
        output_names=['kinematics_output'],
        dynamic_axes={'imu_input': {0: 'batch_size'}, 'kinematics_output': {0: 'batch_size'}}
    )
    print(f"Exported clean ONNX model to {onnx_path} ({os.path.getsize(onnx_path)/1024:.1f} KB)")
    
    if os.path.exists(android_assets_dir):
        import shutil
        shutil.copy(onnx_path, os.path.join(android_assets_dir, 'truetrack_model.onnx'))
        print("Updated android_app assets truetrack_model.onnx")

if __name__ == '__main__':
    main()
